services:
  mongo:
    image: mongo:8.0-noble
    ports:
      - "${BACKEND_MONGO_PORT}:27017"
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${BACKEND_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${BACKEND_MONGO_PASSWORD}
  api:
    image: project.docker.comparitiko.dev/sensors-api:latest
    ports:
      - "${BACKEND_APP_PORT:- 8080}:${BACKEND_APP_PORT:- 8080}"
    environment:
      APP_PORT: ${BACKEND_APP_PORT:- 8080}
      ALLOWED_ORIGINS: ${BACKEND_ALLOWED_ORIGINS}
      JWT_SECRET: ${BACKEND_JWT_SECRET}
      JWT_EXP_TIME: ${BACKEND_JWT_EXP_TIME}
      MONGO_USERNAME: ${BACKEND_MONGO_USERNAME}
      MONGO_PASSWORD: ${BACKEND_MONGO_PASSWORD}
      MONGO_HOST: "mongo" # This should be the name of the mongo service
      MONGO_PORT: "27017" # Internal port of the mongo service
      MONGO_DATABASE: ${BACKEND_MONGO_DATABASE}
      MONGO_AUTH_DATABASE: ${BACKEND_MONGO_AUTH_DATABASE}
    depends_on:
      - mongo